# Environment Definitions and Capabilities
# Defines what operations are available in each deployment environment

environments:
  local_docker:
    type: "docker_compose"
    description: "Local development environment using Docker Compose"
    capabilities:
      - "restart_service"
      - "get_logs" 
      - "check_resources"
      - "execute_command"
      - "scale_service"
      - "health_check"
    limits:
      max_concurrent_operations: 5
      operation_timeout: 300
      log_lines_limit: 10000
    connection:
      type: "docker_socket"
      socket_path: "/var/run/docker.sock"
    
  oracle_cloud:
    type: "oci"
    description: "Oracle Cloud Infrastructure deployment"
    capabilities:
      - "restart_service"
      - "get_logs"
      - "check_resources" 
      - "scale_service"
      - "get_metrics"
      - "rolling_update"
      - "backup_service"
    limits:
      max_concurrent_operations: 10
      operation_timeout: 600
      log_lines_limit: 50000
    connection:
      type: "oci_api"
      config_file: "~/.oci/config"
      profile: "DEFAULT"
    
  kubernetes:
    type: "k8s"
    description: "Kubernetes cluster deployment"
    capabilities:
      - "restart_service"
      - "get_logs"
      - "check_resources"
      - "scale_service" 
      - "rolling_update"
      - "get_metrics"
      - "execute_command"
      - "port_forward"
    limits:
      max_concurrent_operations: 15
      operation_timeout: 900
      log_lines_limit: 100000
    connection:
      type: "kubectl"
      config_file: "~/.kube/config"
      context: "default"

# Environment detection rules
detection:
  local_docker:
    indicators:
      - "docker-compose.yml exists"
      - "DOCKER_HOST environment variable"
      - "Docker socket accessible"
    priority: 1
    
  oracle_cloud:
    indicators:
      - "OCI_CONFIG_FILE environment variable"
      - "~/.oci/config exists"
      - "OCI_CLI_PROFILE environment variable"
    priority: 2
    
  kubernetes:
    indicators:
      - "KUBECONFIG environment variable"
      - "~/.kube/config exists"
      - "kubectl command available"
    priority: 3

# Default environment selection
default_environment: "local_docker"

# Environment-specific configurations
configurations:
  monitoring:
    local_docker:
      prometheus_url: "http://prometheus:9090"
      alertmanager_url: "http://alertmanager:9093"
      grafana_url: "http://grafana:3000"
    
    oracle_cloud:
      oci_monitoring_namespace: "autonomous_trading"
      log_group_id: "ocid1.loggroup..."
      
    kubernetes:
      prometheus_namespace: "monitoring"
      metrics_server_enabled: true 